### ISSUE TITLE
Support Link and Content needed

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#114]
A reminder to fill in the Support are (link from site dashboard)

**Comment by Scotttie** [comment]
I've started writing, but will need somewhere to put it - even if it's just a page for now : )
Could be on the old Simple Church Wordpress even - but I assume that needs refurbishing or closing...

**Comment by Scotttie** [comment]
Requested the WP Support site be installed, and I'll start dropping it all in.

**Comment by danlewis** [comment]
Support link added into the dashboard

**Comment by danlewis** [comment]
Support site been worked on by Scott.
