### ISSUE TITLE
User Friendly 500 page (and 404)

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#142]
OOPS! Something went wrong.
We'll take this area of the website back to the workshop and see if we can get it up and running again for you as soon as we can

**Comment by danlewis** [comment]
i may have fixed it so the proper error page comes up

**Comment by Scotttie** [comment]
Have a look at this page's 500 error. This is what prompted me.
https://helloworld1.adventistchurch.com/

**Comment by danlewis** [comment]
Fixed now?

**Comment by danlewis** [comment]
fixed
