### ISSUE TITLE
File Previews

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#143]
It might be useful to be able to view/download uploaded files from within the dashboard. 
eg PDF's and sound files in the File Library, or in the Document list area, or Podcast area too.

Then you can be sure which one you're adding or deleting without having to place it somewhere on the live site and then go and test and see what it is because someone else named and uploaded the file and it doesn't make sense to you.

**Comment by Scotttie** [comment]
also include the URL for reference

**Comment by danlewis** [comment]
Can now copy the URL (unless unsplash image)
Can view File/Original Image (an unsplash image will be redirect to the the unsplash page)
