### ISSUE TITLE
Limit the number of documents to show

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#149]
The Doc list card, particularly if showing in order of date, it be good to have the ability to only show the past X number (maximum) on page, (then a 'view more' link appears??)

however, if the Docs appear in a scroll box, this may not be necessary. 
I fear 300 files being listed uncontained down the page...

**Comment by danlewis** [comment]
the document list card shows up to 5 documents max.
A view all link is also included on widget now.
