### ISSUE TITLE
How to move cards on phone or tablet without a rollover mouse?

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#151]
Can the rollovers be set to apper on first tap for a tablet or phone?
Right now on my phone I can't move or delete a card - assume it's the same on a tablet - though haven't tested.
This 'rollover' usability issue cole be wider elsewhere? Haven't gone looking.

**Comment by danlewis** [comment]
Fixed using the new cards live preview editor
