### ISSUE TITLE
Add 'contact details' card

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#152]
While contact/address details were set to be handled by liquid tags, we probably need a straight 'contact us' card like on Simple 1.0 that can be used instantly by the coming users.

I say this because the minute churches start making their own cards with typed details, they can't be updated via ACloud and we've lost a key purpose of this project's future proofing function.

A thought: could be used on 2 or 3 column cards as: address, map, open times, (if those ones are added to the columns card options.)

**Comment by danlewis** [comment]
contact details are in the footer of all pages and automatically updated from Adventist Cloud. I think this is better then another card.
