### ISSUE TITLE
Mailchimp 'simplification' at Card level, not differentiating on fornt end (or anywhere)

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#158]
When adding a mailchimp embed code, you need to select if you want it simplified or not on the mailing list screen. Might be better to select what style is wanted when adding the mail list 'Card' screen, else you need to add the list twice if you want to run both styles. Not critical , but ideal.

**Comment by danlewis** [comment]
Done

**Comment by Scotttie** [comment]
The non-edited Mail List card is not displaying the Mailchiimp embed. Appears to be the simplified list.
https://dashboard.adventist.place/dashboard/sites/1/pages/15/preview
https://dashboard.adventist.place/dashboard/sites/1/pages/15

**Comment by danlewis** [comment]
I would prefer to keep the current method where the style to display is set when managing the mailing list.
The only reason a site would use the custom version is if they have custom fields in the embed in which case they would always need to use the custom version.
