### ISSUE TITLE
Footer Issues

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#163]
![screen shot 2018-01-16 at 4 11 26 pm](https://user-images.githubusercontent.com/13688091/34972814-21e3f1e2-fad8-11e7-9446-8d311139c89e.png)
1. have the times always display O'clocks with :00 so they line up nicely
2. how does one edit this RHS menu - in the themes area?. There's not much in this menu.
3. copyright 2017>18

**Comment by danlewis** [comment]
Minutes always included.
Footer changed.
Year updates automatically.
