### ISSUE TITLE
Sort Dashboard's 'top 10' sites list by 'most recently updated' or FAVs

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#166]
We agree not many will have more than 10 sites, but if they do, it will be alphabetical and Zack Church will never be on the list even though it's the one always wanted to be updated.

so, when you've compleated everything else in the world, can you order by last updated? 

OR 
have a 'Fav/Star' system that allows you to have certain sites always appear at the top. (even better?)

**Comment by danlewis** [comment]
The dashboard index page will only list sites you are a Admin or Member of. To see all sites you have access to (e.g. if you are an admin or site supporter), go to Sites in the dashboard nav.
