### ISSUE TITLE
Need a conformation for all 'deletes' page/card etc.

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#168]
Clicking 'Delete' nukes a Page OR Card instantly. Not great if there's no undo for our simple users.
A conformation should be there to slow the accidental click when they sneeze...
you can have a lot of hard work blown away if you accidentally delete a card or page.

**Comment by danlewis** [comment]
added confirmation message

**Comment by Scotttie** [comment]
Deleting page conformation works, (thx!) but can it please be added to deleting Cards on a Page also? 
Some cards can have considerable work put into them and they can be zapped in one click.

**Comment by Scotttie** [comment]
Delete is nested between Edit and Add - FAR to easy to lose a card in one click.

**Comment by danlewis** [comment]
Delete confirmation for cards added
