### ISSUE TITLE
Syncing name Changes in Cloud and Place

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#170]
See screenshot. If a place changes its name in AdPlace, particularly if it's a radically different 'custom edited' name to what's in AdCloud, or is a new name all together updated only in AdPlace, then what is in AdCloud could be outdated and get a little lost - if the new name is used but not noted in AdCloud. 

Can there be a way to display both names together, in both systems, or... I'm not sure what the answer is, or even what the question is, but see the screen shot and feel the vibe of what the issue is.

![screen shot 2018-02-01 at 12 40 10 pm](https://user-images.githubusercontent.com/13688091/35656855-aa80d674-074d-11e8-94cb-a5d5b5039b92.png)

Not urgent.
NOTE, searching on AdClod for the 'new name' in AdPlace brings no results (eg Demodale), so someone may try adding a new entry for this renamed place not knowing the old name, whcih was updated in AdPlace......dunno.

**Comment by danlewis** [comment]
A place in the future may have multiple sites and hence different site names are possible.
A site may also choose to go with a variation of their name which is fine. If there actually place name has changed they should still ideally use suggest a change.
