### ISSUE TITLE
Tidy up Social Account 'Edit' and 'View'

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#174]
A little confusing: if you click on a social account's name you get one screen, but the menu dots>edit you get another. There's no intuition there for a simple user.

Can we either: 
Have the editing link in the menu go to the same page as clicking on the name goes to, AND maybe left align the pencil to edit the name.
or
remove the menu dots and have everything on the accounts page (inc a delete button)

**Comment by danlewis** [comment]
editing of social accounts removed to avoid other issues.
