### ISSUE TITLE
Submission view/reply process tweek

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#181]
I understand the reasoning but Submissions are a little cumbersome presently, perhaps more hindering then helpful.

- Form is submitted 
(all good so far)

- All 'Admins/Members' get an email. 
(can't have an official 'church' email used, nor exclude, say, junior webmaster, from getting the submission notifications - everyone gets it, like it or not.)

- notification email does not show any of what the message is, or who from, could be daily spam 
(who and first 100 characters would be good in the notification email to determine if it's worth login in to administer or the urgency)

- cannot quickly reply, especially if getting the notification on mobile email. After getting the notification email, you can't just reply and be done: You need to log in, find the message, copy the address, go back and create a new email message with the email address and THEN reply "yes". I understand the need for read/reply management, and the avoidance of in-system email sending, but this seems painful.

- there's also no way to note something has been replied to (and by who) or leave a basic admin note.
 
Can this flow get a rethink for practicality some time?
Maybe minimum, add some helpful info to the notification email, AND have the email address of the sender as a clickable link on the submissions page, which will open the message in their default email client.
</rant>

**Comment by danlewis** [comment]
Submission process rewritten :)
