### ISSUE TITLE
Q: when does an event disappear?

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#202]
Q1, when does an event disapear is it after start of event, or after end of event?

eg, I'm running 5 minutes late, what's the time and address of that event.  Can I still see it on the website or has the event moved on?

Q2, how frequent are FB events fetched? once daily?

Q3,  what does "Share event with nearby sites? A street address is required to share"
actually mean? 
How can I show events near me on my site? or is this only for Conferences missions to ''extract' the events into something cleverly programed?

Q4, can an event belong to more than one calendar? eg, a pathfinder fundraiser evening could be in the PF calendar and also the church calendar.

Q5. while I'm here, the Embed code Widget, What specific code does it allow or not allow?

**Comment by danlewis** [comment]
Q1. If there is any end date - 1 day after. If there is no end date - 1 day after the start date.
Q2. Daily
Q3. At present this doesn't do anything. I've now hidden it.
Q4. Only one calendar. I think more than one might unnecessarily complicate the feature. The events page displays events from all calendars any way.
Q5. it would actually allow anything at present..
