### ISSUE TITLE
Spacer Widget Changes

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#203]
1. have a name on the widget (it gets lost in the editor)
2. be able to set the vertical spacing distance, even if just small medium and large
3. be able to add a coloured line (and thickness?)(set to the themes css?)

**Comment by Scotttie** [comment]
1. I cannot see a name on my widget in the live preview screen. It's a blank area you need to click 'randomly' to find.
2. are you saying you'll add a <hr> to the Text Widget? I was suggesting that a user coudl slightly ajust the spacers space it puts in. not important
3. a HR would be nice. Somewhere. Or i'll upload an image of a line and use the image widget, like the old days! haha.

**Comment by danlewis** [comment]
1. you'll have to show me as the widget name shows for me
3. hr added to text editor

**Comment by Scotttie** [comment]
I ‘see’ the issue!!
it’s when I first put the spacer in, the name does not appear until I refresh the page, or go out and in.
That’s less of a problem then.

Good work, with the hr.. ☺


Scott Wegener — Web Coordinator

AdventistBookCentre.com.au<http://www.adventistbookcentre.com.au/>
Christian resources in just a click!

**Comment by danlewis** [comment]
Spacer Widget Removed :)
