### ISSUE TITLE
Mailing list Widget, 'not simple' version, does not close widget window when saving widget .

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#204]
Works saving a 'simple' Mailchimp form, but not the 'complex' form. I change to a complex form on the widget and click save. I see it change in the background but the window doesn't close, and if i click out of the widget area, it's there but i can no longer edit ANY widgets until a reload.

**Comment by danlewis** [comment]
I'm now striping the script out of the embed code which fixes the issue. The user doesn't have to do anything different
