### ISSUE TITLE
uploaded image 'pencil' not working.

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#208]
I click on the pencil after uploading an image and it doesn't take me to the edit details screen. the window does toggle left and right a few pixels mysteriously however.

also

It be nice if you could add/select the image you just uploaded on the upload success page instead of needing to go over to My images tab.

AND 
the 'my images' tab's search has a filter icon which doesn't always work, or is irrelevant on the image screen (filter by file type)

**Comment by danlewis** [comment]
1. You may not have scrolled down to see the edit screen. Seems to work for me.

2. Yes it would be - added

3. Filter removed as there wasn't really any filtering happening
