### ISSUE TITLE
Ability to add an 'independent' video url to Video Feature Widget

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#209]
Currently, you can only add videos to your site if they are a part of a playlist that is also added to your site - unless you use the embed widget, which is a tad messy for some simple users.

Say the youth Dept has a pathfinder camporee video, the user wants to add it to their pathfinder page, they don't even have a Youtube account.

Instead of embedding, it would be good if they could drop in the Youtube URL into the Video Featured Widget, for example, and easily have the one off video drop in and be formatted consistently.

**Comment by danlewis** [comment]
The video iframe code has lots of important stuff - e.g. the actual URL for the video embed (different from the videos website URL), preferences for displaying it, width and height information so we know what aspect ratio to show the video in (without knowing the aspect ration the video can have large spacing gaps above and below it).

Having videos added via an iframe does all of the above for any video service :)
