### ISSUE TITLE
'New User' page should have text for if a user isn't a user yet....

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#216]
eg https://dashboard.adventist.place/dashboard/sites/18/memberships/new

if i try add someone, but they don't have an account yet to be found in the search, there should be some text on the screen which says:

" Can't find user? They must have logged into the Adventist Place dashboard, with their myAdventist account, at least once before you can add them to your site. "

ACTUALLY, can we have a 'send invitation' feature? Just a thought. It's clunky at the moment to add a user.

**Comment by danlewis** [comment]
Feature Added:

Invite users to join a team. Add the users email address and role, and an invite email will be sent to them. User can click link in email to take them to the dashboard and there membership will be automatically created.
Invitations expire after 30 days but can be resent from dashboard > users
