### ISSUE TITLE
Image Widget links

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#218]
1. be good to have the option to link an image widget also.

2. it would be nice to have the new tab/window target option on the image & card widgets just as there is in the Text widget for external links.

**Comment by danlewis** [comment]
Added target to card widget.

Adding a URL to an image widget is bit too ambiguous as the widget has a title and image. Therefore it becomes confusing as to what part of the widget should the URL apply to.. Does it put a link on the whole widget, the title or the image. I would suggest that if users want an image to link, the card widget would be the better place.
