### ISSUE TITLE
Remove Spouse from Team members display

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#226]
![spouse](https://user-images.githubusercontent.com/13688091/40403360-e1034bfc-5e94-11e8-9b1a-e626e2db38ea.jpg)
Not sure of the point or preference to list a spouse here?

**Comment by danlewis** [comment]
Spouse isn't a field we track - someone has added spouse as the biography of the David Edgar unfortunately. I have now removed this from his biography and website should update by tomorrow I believe unless it's done manually

**Comment by Scotttie** [comment]
Thanks for nutting out. I assumed it was a field and freaked out when I spotted it haha.
Discovery added?
Such should go in notes, i assume - if there's a notes area.
Why does on need to record spouse?? Befuddled.
