### ISSUE TITLE
Search engine title and descriptions/meta

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#228]
Google result:

**Albany Church: Home**
https://albany.adventist.place/
Albany. Seventh-day Adventist Church. Ministries. A ministry for everyone · Visiting our church. What to expect? Our Stories. See how God has transformed lives ...

No Adventist in this title link. Should we force the long name?

Also - ability to set the description for Google to show in results would be good for those who care.

**Comment by Scotttie** [comment]
Oh, this was the question form a Conference Comms person that lead to this ticket:

"And who edits the meta descriptions to optimise SEO?"

**Comment by Scotttie** [comment]
Our Seventh-day Adventist church is a Christian community meeting every Saturday morning for a family-friendly Bible study and church service. Come and join us!

Having a look through google: most top results have 'suburb adventist church' or 'suburb seventh-day adventist church', none- that came up - have 'suburb church' which most of ours are and is uninformative.

**Comment by danlewis** [comment]
- Site Settings: add default site description for SEO
- Page > Settings: optional set a seo title and description. If not, the page title will be used and default site description
- If a page has a banner image, the banner image url will be used as in the  open graph image. In all other cases a picture of the adventist logo is used

**Comment by danlewis** [comment]
I’ve just run a script which finds all sites that were migrated and have the name “[site.short_name] Church” and renames them to “[site.short_name] Adventist Church” presuming the new name isn’t longer than 35 chars.
