### ISSUE TITLE
Translations: Tok Pisin offer

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#23]
From: Hawai Nick Kuvai <hawaik@upng.ac.pg>

Language: Tok Pisin

Message Body:
I speak and write in English and Tok Pisin fluently.

**Comment by Scotttie** [comment]
Another offer:

From: WESLEY SAIHENEN
Sent: Tuesday, 11 April 2017 7:49:03 PM (UTC+10:00) Canberra, Melbourne, Sydney
To: Webmaster AMN
Subject: Simple Church Translator
From: WESLEY SAIHENEN <emmanuel4tec@gmail.com>
Language: pidgin (png)
Message Body:
Papua new Guinea needs to know Jesus Gospel... Register me as volunteer.

**Comment by danlewis** [comment]
No longer offer multi language support.
