### ISSUE TITLE
Header logo/design

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#233]
A handful of people have voiced so far, and one even adamantly opposed to there being no logo in the header.
Seems fair and reasonable to get some branding up there and the coding can be achieved I'm sure for both views.
Options:
- With or without an ‘orange’ box - that could change colour in the theme setting 
- With or without the logo text below it, or beside it? 
- turn logo off all together, like it is now? 
- Put your own logo there, with very specific dimensions? EG ADRA Opshop is a different logo.
- and then there's the 6-1 logo - best done in the banner perhaps, but needs mentioning here as it gets brought up. Maybe THAT is a second theme/header, where there's a significant large 6-1 logo scheme.
- A different home header compared to the other page headers, maybe showing a large logo on home and smaller with title on all other pages

**Comment by danlewis** [comment]
logo added
