### ISSUE TITLE
Front end not refreshing: Documents and Menu links

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#234]
the document displated on the Widget does not refresh quickly at all, while if you click 'view all' you can see the actual updated document is htere

also, from redcliff else, perhaps related: "While I'm here, I noticed a slight bug. I created a sub-menu/child item which I later deleted. And I found that this ghost of a link hung around for some time on the live site, but was gone in the dashboard. It was only when I checked the site this morning that I noticed it was gone."

**Comment by danlewis** [comment]
This issue should now be resolved. Please verify

**Comment by danlewis** [comment]
Please open if issue still exists
