### ISSUE TITLE
Self adjust Times (and other cloud content?)

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#235]
Maybe there is a case, or not, to allow SOME edits to go straight through to cloud, like the times.

below example is maybe not idea, but gives one example of application:
"It would be good if the opening hours could be easily customized by the admin. The reason for this request is that I would like to have the church open more throughout the week to allow members of the church or community to visit me at the church, however I need a system where I can easily change the availability if I am going to be away for a visitation or a bible study. I would like it if I could simply tell the church to check the website to see if I am available or not. This change would allow me to advertise when the church will be opened and also to ensure that people know when I am not available."
(maybe this even falls into another 'booking' feature)

Reported anyway...

**Comment by danlewis** [comment]
I would suggest changes like this aren't opening times. This seems more like the pastors personal schedule and I'm not sure where the best place for that would be.

Opening Times shouldn't change regularly as it has a flow on effect to all other apps on Adventist Cloud and possibly services like Google Places, etc if we eventually add those into Cloud.
