### ISSUE TITLE
New User requests come in as 'Members'

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#238]
If a site exists but has no Admin (usually an old Simple Church migration site) AND when a User requests to be an admin to that existing, admin-less site, they are set to 'member' and waiting for approval. No slack message either. 

Can we have:

1. user waiting for approval is automatically set to admin (not member) by default if there's no other admin in the site yet
2. a Slack notification of the user request if there's no Admin. (But not if there is an Admin in there)
3. I'm not sure what notifications site supporters should get...

**Comment by danlewis** [comment]
should be fixed - please check

**Comment by danlewis** [comment]
closing.. Please reopen if issue still
