### ISSUE TITLE
Resource Group tweaks

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#242]
1. Is the word 'Resources' below the group title necessary?  
It does look a little silly in this pictured context, which is perhaps the most common context.

![screen shot 2018-08-22 at 3 07 23 pm](https://user-images.githubusercontent.com/13688091/44443879-62674e80-a61d-11e8-8a3b-1621f5f5539a.png)

2. The title and file names being identical is not useful but will no doubt be common, or the file name might even be ugly and should't be shown.
Would it be more beneficial to display something like "'file type' download". eg "PDF Download". Additional reason: if there's two files of the same name but different type, the links will look identical and be confusing. eg bulletin.pdf bulletin.doc.

**Comment by danlewis** [comment]
If only only file for a resource, the link will show the label "Download" otherwise resort to the filename.
