### ISSUE TITLE
People Widget style needs containing when to the L or R of other Widgets

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#260]
People widgets when placed next to other widgets have the text exiting the box, despite having ample space. 
See attached:
![bug](https://user-images.githubusercontent.com/13688091/53526821-4cd96100-3b39-11e9-8096-6a7614304b6a.jpg)

**Comment by danlewis** [comment]
This should now be corrected

**Comment by Scotttie** [comment]
not fixed for 2 or 3 column widgets, see:
https://demodale.adventist.place/test

**Comment by Scotttie** [comment]
never mind - was caching...
