### ISSUE TITLE
Add ability to have scripts in body.

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#270]
eg for Facebook chat feature
And what about in the Header tags too?

"Many tracking tools or other web services (e.g. Facebook Messenger Customer chat) can integrate with web sites by putting their code right under the body tag. I'd love if each page could have a setting under each page where more advanced users could implement their own bits of code to run right under this body tag. Would allow for huge flexibility for things like this." - Tim H

**Comment by Scotttie** [comment]
I think it's this:
https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/

**Comment by danlewis** [comment]
Done
