### ISSUE TITLE
Livestream Feature Broken - does not display a livestream

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#272]
I'm sure livestream used to work, to some extent, but not now. 
Tried Youtube and livestream.com feeds and get 'refused to connect'  on fornt end see https://demodale.adventist.place/livestreams/2
some times it won't save a feed, even without a validation error.

Not certain the Dates feature is working right either. One example, I saw a 'Livestreamed on 23 Aug 2019' when it was only the 22nd of Aug 2019. Also saw 'starts [date]' when in fact the date was past.

Perhaps we can disable the Livestream feature, if you can't fix it easily, as YouTube and Livestream.com have 'embed' codes that can be dropped easily in the Embed Code Widget?

Otherwise my questions, when fixed, to aid my documentation are also:
-What if church weekly livestreams? do they need to add new livestream each week? 
-What does start time actually do - before and after?
-Is 'all day' mean it streams 24/7 or just that day?

**Comment by danlewis** [comment]
- yes they need to add/update the stream each week - there effectively seperate livestream events with different URLS
- start time only helps to inform users when they should watch the livestream, and when to display it on the website
-all day means 24/7

**Comment by danlewis** [comment]
All fixed up i believe
