### ISSUE TITLE
Daylight savings messing with reoccurring events?

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#273]
Michael of Redcliff added a recurring event with all the same start times. It seems the daylight saving is messing with the start times later in the year (Adding an hour to them). 

![69128827_2390779971204767_5500531407300067328_n](https://user-images.githubusercontent.com/13688091/63485615-673c3800-c4e7-11e9-8a08-09fdb9463b3a.jpg)

2. Also, "all the dates and times are not listed when editing."

**Comment by danlewis** [comment]
Fixed
