### ISSUE TITLE
School default ABOUT Card info

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#63]
Below is some proposed details for a default School ABOUT card:

Quality Education

We encourage
[options to cycle through include]
Excellence
Compassion
Humility
Respect
Integrity
Justice
Responsibility
Hope

Our school provides Christ-centered education for the community. Our mission is to develop children of character in a faith nurturing environment that promotes academic excellence. We are committed provide opportunities for all student to achieve their maximum development intellectually, spiritually, socially and physically.
We are proudly owned and operated by the Seventh-day Adventist Church and provide a nurturing and caring learning environment where Christian values are upheld.

[image] This is tricky, as Island school kids and conditions are vastly different to Aust schools for example.
Here's some generic concepts for an image:

http://picovico.com/wp-content/uploads/2015/11/yourstory-education.jpg
http://www.thecitizen.org.au/sites/default/files/sustainability%20-%20Copy.jpeg
http://wonderopolis.org/wp-content/uploads//2013/06/dreamstime_xxl_13789480.jpg
https://nces.ed.gov/programs/coe/images/nav/coe_hp_new.png

**Comment by danlewis** [comment]
I've now updated the about page with a school specific card on the default template using your provided text.
