### ISSUE TITLE
We need an Island context 'about Adventist' Video

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#8]
Our video has no islanders and is unrelateable, say feedback.

**Comment by Scotttie** [comment]
Here is another 'official' option:
https://www.youtube.com/watch?v=l8g2Z1l9zzE&feature=youtu.be

**Comment by Scotttie** [comment]
We could have a set of available videos, like we do banners, that can be selected from.

**Comment by danlewis** [comment]
Sites can now remove/change the Video widget as they wish
